#pragma once

#include "NativeGameplayTags.h"

namespace AdaptiveEnvGameplayTags
{
	ADAPTIVEENVRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Behaviour_Move);
	ADAPTIVEENVRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Behaviour_Dwell);
	ADAPTIVEENVRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Behaviour_Sprint);
	ADAPTIVEENVRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Behaviour_Collect);
	ADAPTIVEENVRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Behaviour_Combat);
}
